services:
  # PostgreSQL DB for custom query and value set storage
  db:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=tefca_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 20

  # Next.js app with Flyway
  tefca-viewer:
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: ./containers/tefca-viewer/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:pw@db:5432/tefca_db
      - INSTALLDIR=/blah
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/conf/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      db:
        condition: service_healthy
    # command: >
    #   sh -c "
    #   flyway -configFiles=/flywayHERE/flyway/conf/flyway.conf -schemas=public -connectRetries=60 migrate &&
    #   node containers/tefca-viewer/server.js"
    # command: >
    #   sh -c "./flywayHERE/flyway --help"
    # command: ls ./flywayHERE
    # entrypoint: ["flyway", "--help"]
    # entrypoint: ["sh", "-c", "flyway -configFiles=/flyway/conf/flyway.conf -schemas=public -connectRetries=60 migrate && node containers/tefca-viewer/server.js"]
