services:
  tefca-viewer:
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: ./containers/tefca-viewer/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
