services:
  # PostgreSQL DB for custom query and value set storage
  db:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    # Once we have the migrations set up, we may need to use a mounted volume
    # copy to get them into the container and create our table structure.
    # The excerpt below is copied from the ECR Viewer, which has the most
    # similar structure to what we're doing.
    # volumes:
    #  - ./sql/:/docker-entrypoint-initdb.d/
    #  - ./seed-scripts/sql/:/docker-entrypoint-initdb.d/
    #  - ./seed-scripts/sql/.pgpass/:/usr/local/lib/.pgpass
    env_file:
      - "./tefca.env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 20

  # Next.js app
  tefca-viewer:
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: ./containers/tefca-viewer/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - "./tefca.env"
    environment:
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
