services:
  # PostgreSQL DB for custom query and value set storage
  db:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=tefca_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 20
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./generate-certificates.sh:/docker-entrypoint-initdb.d/generate-certificates.sh
    command: >
      /bin/sh -c "chown -R postgres:postgres /var/lib/postgresql/data && 
      apk add --no-cache openssl su-exec && 
      chmod +x /docker-entrypoint-initdb.d/generate-certificates.sh && 
      su-exec postgres /docker-entrypoint-initdb.d/generate-certificates.sh && 
      postgres -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key"

  # Flyway migrations and DB version control
  flyway:
    image: flyway/flyway:10.16-alpine
    command: -configFiles=/flyway/conf/flyway.conf -schemas=public -connectRetries=60 migrate
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/conf/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      db:
        condition: service_started

  # Next.js app
  tefca-viewer:
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: ./containers/tefca-viewer/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:pw@db:5432/tefca_db?sslmode=require
    depends_on:
      db:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
