comment:
  layout: "diff, flags, files"
  behavior: default
coverage:
  range: 85...100
  status:
    project:
      default:
        target: 95%
        threshold: 10%
        flags:
          - unit-tests
    patch:
      default:
        target: 95%
        threshold: 10%
        flags:
          - unit-tests
