requiredFields:
  - fieldName: Status
    cdaPath: ClinicalDocument/component/structuredBody/component/section/entry/act/code
    attributes:
    - attributeName: code
  - fieldName: Conditions
    cdaPath: ClinicalDocument/component/structuredBody/component/section/entry/organizer/component/observation/value/code
    textRequired: true
  - fieldName: eICR
    cdaPath: ClinicalDocument/id
    attributes:
      - attributeName: root
  - fieldName: eICR Version Number
    cdaPath: ClinicalDocument/versionNumber
    attributes:
      - attributeName: value
  - fieldName: "Authoring date/time"
    cdaPath: ClinicalDocument/recordTarget/author/time
    attributes:
      - attributeName: value
  - fieldName: First Name
    cdaPath: ClinicalDocument/recordTarget/patientRole/patient/name/given
    textRequired: true
    attributes:
      - attributeName: use
        regEx: /L/
  - fieldName: Middle Name
    cdaPath: ClinicalDocument/recordTarget/patientRole/patient/name/given
    textRequired: true
    attributes:
      - attributeName: use
        regEx: /L/
      - attributeName: qualifer
        regEx: /IN/
  - fieldName: Last Name
    cdaPath: ClinicalDocument/recordTarget/patientRole/patient/name/family
    attributes:
      - attributeName: use
        regEx: /L/
    textRequired: true
  - fieldName: DOB
    cdaPath: ClinicalDocument/recordTarget/patientRole/patient/birthTime
    textRequired: true
  - fieldName: MRN
    cdaPath: ClinicalDocument/recordTarget/patientRole/id/
    attributes:
      - attributeName: extension
      - attributeName: root
  - fieldName: Sex
    cdaPath: ClinicalDocument/recordTarget/patientRole/patient/administrativeGenderCode
    textRequired: true
    regEx: /F|M|O|U/
  - fieldName: Street Address
    cdaPath: ClinicalDocument/recordTarget/patientRole/addr/streetAddressLine
    textRequired: true
  - fieldName: City
    cdaPath: ClinicalDocument/recordTarget/patientRole/addr/city
    textRequired: true
  - fieldName: State
    cdaPath: ClinicalDocument/recordTarget/patientRole/addr/state
    textRequired: true
  - fieldName: Country
    cdaPath: ClinicalDocument/recordTarget/patientRole/addr/country
    textRequired: true
  - fieldName: Zip
    cdaPath: ClinicalDocument/recordTarget/patientRole/addr/postalCode
    textRequired: true
    regEx: /[0-9]{5}(?:-[0-9]{4})?/
  - fieldName: Provider ID
    cdaPath:  ClinicalDocument/componentOf/encompassingEncounter/responsibleParty/assignedEntity/id
    attributes:
      - attributeName: extension
      - attributeName: root
  # - fieldName: 
  #   cdaPath:
  #   attributes:
  #     - attributeName: example
  #       regEx:
  #     - attributeName: example
  #       regEx:
  #   textRequired: false
  #   requiredIf:
  #     otherFieldName:
  #     otherFieldValue:
  #     otherFieldAttribute:
  #     otherFieldAttributeValue:
