services:
  orchestration-service:
    platform: linux/amd64
    build:
      context: ../../orchestration/
    depends_on:
      - fhir-converter-service
      - ingestion-service
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
    env_file:
      - ../../orchestration/.env

  fhir-converter-service:
    build:
      context: ../../fhir-converter/
    ports:
      - "8082:8080"

  ingestion-service:
    platform: linux/amd64
    build:
      context: ../../ingestion
    ports:
      - "8083:8080"
    logging:
      driver: "json-file"
    environment:
      SMARTY_AUTH_ID: ${SMARTY_AUTH_ID}
      SMARTY_AUTH_TOKEN: ${SMARTY_AUTH_TOKEN}

  convert-data:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./sql:/code/sql
