services:
  orchestration-service:
    platform: linux/amd64
    build:
      context: ../../orchestration/
    depends_on:
      - validation-service
      - fhir-converter-service
      - ingestion-service
      - message-parser-service
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
    env_file:
      - ../../orchestration/.env

  validation-service:
    platform: linux/amd64
    build:
      context: ../../validation
    ports:
      - "8081:8080"
    logging:
      driver: "json-file"

  fhir-converter-service:
    build:
      context: ../../fhir-converter/
    ports:
      - "8082:8080"

  ingestion-service:
    platform: linux/amd64
    build:
      context: ../../ingestion
    ports:
      - "8083:8080"
    logging:
      driver: "json-file"
    environment:
      SMARTY_AUTH_ID: ${SMARTY_AUTH_ID}
      SMARTY_AUTH_TOKEN: ${SMARTY_AUTH_TOKEN}

  message-parser-service:
    platform: linux/amd64
    build:
      context: ../../message-parser
    ports:
      - "8084:8080"
    logging:
      driver: "json-file"

  convert-data:
    build: .
    depends_on:
      - orchestration-service
    ports:
      - "8085:8080"
    volumes:
      - ./sql:/code/sql
