name: Register for the Geocoding Beta Program
description: Subsidized geocoding services for State, Territorial, Local, and Tribal health departments
title: "[Affiliated Jurisdiction] Geocoding Beta Program"
labels: ["geocoding-beta"]
assignees:
  - millzpaugh
  - nagelanukuna
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in the PHDI Geocoding Beta Partnership! 
        See full details about the beta [here](https://github.com/CDCgov/phdi/blob/main/docs/geocoding_pilot/overview.md). 
        Please add your jurisdiction to the title placeholder `[Affiliated Jurisdiction]` and fill in the information below. We will be in touch shortly with next steps.
  - type: input
    id: name
    attributes:
      label: Name
      description: "Please provide your full name"
    validations:
      required: true
  - type: input
    id: role
    attributes:
      label: Role
      description: "Please provide your role within your organization"
    validations:
      required: true
  - type: input
    id: organization
    attributes:
      label: Affiliated Public Health Department
      description: "Please provide the name of your organization (link URL if possible)"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        As part of creating this ticket, you'll need to schedule time to connect with a PHDI team member.
        Schedule a meeting here via [Calendly](https://calendly.com/ann-299/geocoding-beta-partner).
  - type: checkboxes
    attributes:
      label: Meeting Confirmation
      description: "Scheduling a meeting helps ensure we can get you onboarded as quickly as possible."
      options:
        - label: "I scheduled time to receive my subsidized Smarty license"
          required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context or questions
      description: "Please provide any additional context or questions you have here."
    validations:
      required: false
  