name: Bug Report
description: File a bug report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behavior in the existing issues.

        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: "What opererating system are you using?"
      options:
        - Windows
        - MacOS
        - Linux
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Description
      description: "Please provide a clear and concise description of what feature is not working."
      placeholder: "Example: The geocode_from_str() function in the geospatial.smarty module is returning a 401 error even though I have provided my license."
    validations:
      required: true
  - type: input
    id: impact
    attributes:
      label: Impact
      description: "Please describe the impact this bug is causing to you and/or your organization."
      placeholder: "Example: We are at risk of failing to meet our reporting requirements because we are unable to add the necessary lat/lon data."
    validations:
      required: true
  - type: input
    id: replication
    attributes:
      label: Steps to Reproduce
      description: "Please provide the steps to reproduce the behavior"
      placeholder: |
        1. Import the geocoding functionality by running "import phdi.geospatial"
        2. Create a new variable called address and set it to "123 Main St Washington, DC"
        3. Create a new SmartyGeocodeClient by running "client = SmartyGeocodeClient(auth_id=..., auth_token=...)"
        4. Attempt to geocode the address by running "client.geocode_from_str(address)"
        5. Observe that it does not complete the request
    validations:
      required: true
  - type: input
    id: expectation
    attributes:
      label: Expected Behavior
      description: "Please provide a clear and concise description of what you expected to happen."
      placeholder: "Example: The function should return a standardized address with lat and lon."
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: "Please add any other context about the problem here."
      placeholder: "Example: This was working yesterday, and just started acting up today."
    validations:
      required: false
