name: Support and Maintenance
description: “Ask questions and make requests related to support and maintenance.”
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Describe your problem."
      placeholder: "Example: I'm interested in using the PHDI SDK, but I can't figure out how to install it."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Desired Help
      description: "Describe how you'd like us to help."
      placeholder: "Example: Can you point me to any documentation you have on how to get started with your tools?"
    validations:
      required: true
