name: Support and Maintenance
description: Questions and requests related to organizational support and maintenance
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "What type of help do you need?"
      placeholder: "Example: I am interested in using the PHDI SDK, but I cannot figure out how to install it."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Desired Help
      description: "Please describe how you'd like us to help."
      placeholder: "Example: Can you please point me to any documentation you have on how to get started with your tools?"
    validations:
      required: true
