services:
  # PostgreSQL database
  db:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - ./seed-scripts/sql/:/docker-entrypoint-initdb.d/
      - ./seed-scripts/sql/.pgpass/:/usr/local/lib/.pgpass
    environment:
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=ecr_viewer_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 20
    networks:
      - ecr-viewer

  # Azure Blob Storage emulator
  azure-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000 -l data"
    ports:
      - "10000:10000"
    networks:
      - ecr-viewer

  # AWS S3 Storage emulator
  aws-storage:
    image: gresau/localstack-persist:3
    ports:
      - "4566:4566"
    volumes:
      - "./volume:/persisted-data"
    networks:
      - ecr-viewer

networks:
  ecr-viewer:
    name: "ecr_viewer_network"
    external: true
