services:
  # Azure Blob Storage emulator
  azure-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000 -l data"
    ports:
      - "10000:10000"

  # AWS S3 Storage emulator
  aws-storage:
    image: gresau/localstack-persist:3
    ports:
      - "4566:4566"
    volumes:
      - "./volume:/persisted-data"
