# This exists because it conflicts with orchestration if Jaeger and otel are here
services:
  db:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    volumes:
      - ./seed-scripts/sql/:/docker-entrypoint-initdb.d/
      - ./seed-scripts/sql/.pgpass/:/usr/local/lib/.pgpass
    environment:
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=ecr_viewer_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 20

  # Next.js app
  ecr-viewer:
    build:
      context: ../../
      dockerfile: ./containers/ecr-viewer/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/app:/app
    environment:
      - DATABASE_URL=postgres://postgres:pw@db:5432/ecr_viewer_db
    depends_on:
      db:
        condition: service_healthy
