services:
  # Next.js app
  ecr-viewer:
    build:
      context: ../../
      dockerfile: ./containers/ecr-viewer/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - APP_ENV=${APP_ENV:-dev}
    env_file:
      - .env.local
    networks:
      - ecr-viewer

networks:
  ecr-viewer:
    name: "ecr_viewer_network"
