FROM node:18-alpine

WORKDIR /code

# Copy package.json and package-lock.json files
COPY containers/ecr-viewer/package.json containers/ecr-viewer/package-lock.json /code/ecr-viewer/
COPY shared-resources/package.json shared-resources/package-lock.json /code/shared-resources/

# Install dependencies for shared-resources
WORKDIR /code/shared-resources
RUN npm ci

# Install dependencies for ecr-viewer
WORKDIR /code/ecr-viewer
RUN npm install

# Copy the application code
COPY containers/ecr-viewer /code/ecr-viewer
COPY shared-resources /code/shared-resources

# Remove any existing data in the shared folder and copy the shared resources
RUN rm -rf /code/ecr-viewer/src/app/shared/* && cp -r /code/shared-resources/src/* /code/ecr-viewer/src/app/shared/

WORKDIR /code/ecr-viewer

EXPOSE 3000

ENV OTEL_TRACES_EXPORTER=otlp
ENV OTEL_METRICS_EXPORTER=otlp
ENV OTEL_LOGS_EXPORTER=none

# Prometheus preferred transfer is via HTTP
ENV OTEL_EXPORTER_OTLP_METRICS_PROTOCOL=http/protobuf
ENV OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otel-collector:4318/v1/metrics

# Jaeger preferred routing is gRPC for native OTLP
ENV OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc
ENV OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4318/v1/traces

CMD ["npm", "run", "dev"]
