version: "3.8"

services:
  validation:
    build:
      context: ../validation/
      no_cache: true
    image: validation
    ports:
      - "8081:8080"
    restart: unless-stopped

  fhir-converter:
    build:
      context: ../fhir-converter/
      no_cache: true
    image: fhir-converter
    ports:
      - "8082:8080"
    restart: unless-stopped

  message-parser:
    build:
      context: ../message-parser/
      no_cache: true
    image: message-parser
    ports:
      - "8085:8080"
    restart: unless-stopped

  ingestion:
    build:
      context: ../ingestion/
      no_cache: true
    image: ingestion
    ports:
      - "8083:8080"
    restart: unless-stopped

  ecr-viewer:
    build:
      context: ../ecr-viewer/
      no_cache: true
    image: ecr-viewer
    ports:
      - "3000:8080"
    restart: unless-stopped

  orchestration:
    build: .
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    depends_on:
      - validation
      - fhir-converter
      - message-parser
      - ingestion
      - ecr-viewer
    env_file:
      - .env
