version: "3.8"

services:
  # Python seeding
  seed-db:
    build:
      context: "../ecr-viewer/seed-scripts"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=ecr_viewer_db
      - DATABASE_CONNECTION=db
      - DATABASE_PORT=5432
    depends_on:
      db:
        condition: service_healthy
