name: "List Containers"
description: "Generate a list of subdirectories within containers/."

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get install jq
    - name: Generate list of directories within containers/
      shell: bash
      working-directory: ./containers
      # use jq to produce json output and filter out the empty item caused by final newline
      run: |
        echo "containers=$(ls -d * | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_ENV
  - name: Use the value
    run: |
      echo "${{ env.containers }}"