apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: record-linkage-app
  name: record-linkage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: record-linkage-app
  template:
    metadata:
      labels:
        app: record-linkage-app
    spec:
      containers:
      - name: record-linkage-app
        image: ghcr.io/cdcgov/phdi/record-linkage:v1.0.7
        ports:
        - containerPort: 8000
        env:
        - name: MPI_DB_TYPE
          valueFrom:
            secretKeyRef:
              name: mpi-secrets
              key: db_type
        - name: MPI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mpi-secrets
              key: db_password
        - name: MPI_DBNAME
          valueFrom:
            secretKeyRef:
              name: mpi-secrets
              key: db_name
        - name: MPI_HOST
          valueFrom:
            secretKeyRef:
              name: mpi-secrets
              key: db_host
        - name: MPI_USER
          valueFrom:
            secretKeyRef:
              name: mpi-secrets
              key: db_user
        - name: MPI_PORT
          valueFrom:
            secretKeyRef:
              name: mpi-secrets
              key: db_port
        - name: MPI_PATIENT_TABLE
          valueFrom:
            secretKeyRef:
              name: mpi-secrets
              key: patient_table
        - name: MPI_PERSON_TABLE
          valueFrom:
            secretKeyRef:
              name: mpi-secrets
              key: person_table
---
apiVersion: v1
kind: Service
metadata:
  name: record-linkage-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: record-linkage-app