apiVersion: v1
kind: Secret
metadata:
  name: mpi-secrets
type: Opaque
stringData:
  db_type: "postgres"
  db_password: "$password"
  db_name: "$dbName"
  db_host: "$fqdn"
  db_user: "postgres"
  db_port: "5432"
  patient_table: "patient"
  person_table: "person"