# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  secretObjects:                                 # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - secretName: ingestion-secrets
    type: Opaque
    data:
    # - objectName: <objectAlias from objects in parameters>   # name of the mounted content to sync. this could be the object name or object alias
    #   key: <key of object to be accessed from deployment apps>
    - objectName: smarty-auth-id                    # name of the mounted content to sync. this could be the object name or object alias
      key: smarty-auth-id-key
    - objectName: smarty-auth-token
      key: smarty-auth-token-key
    - objectName: ingestion-url
      key: ingestion-url-key
  - secretName: record-linkage-secrets
    type: Opaque
    data:
      - objectName: mpi-db-type
        key: mpi-db-type-key
      - objectName: mpi-password
        key: mpi-password-key
      - objectName: mpi-dbname
        key: mpi-dbname-key
      - objectName: mpi-host
        key: mpi-host-key
      - objectName: mpi-user
        key: mpi-user-key
      - objectName: mpi-port
        key: mpi-port-key
      - objectName: mpi-patient-table
        key: mpi-patient-table-key
      - objectName: mpi-person-table
        key: mpi-person-table-key
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: <client Id found by az aks show -g nick-temp -n <kubernetes-cluster-name> --query addonProfiles.azureKeyvaultSecretsProvider.identity.clientId -o tsv> # Set the clientID of the user-assigned managed identity to use
    keyvaultName: <NAME OF KEYVAULT>     # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: smarty-auth-id
          objectAlias: smarty-auth-id
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: smarty-auth-token
          objectAlias: smarty-auth-token
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: mpi-db-type
          objectAlias: mpi-db-type
          objectType: secret
        - |
          objectName: mpi-password
          objectAlias: mpi-password
          objectType: secret
        - |
          objectName: mpi-dbname
          objectAlias: mpi-dbname
          objectType: secret
        - |
          objectName: mpi-host
          objectAlias: mpi-host
          objectType: secret
        - |
          objectName: mpi-user
          objectAlias: mpi-user
          objectType: secret
        - |
          objectName: mpi-port
          objectAlias: mpi-port
          objectType: secret
        - |
          objectName: mpi-patient-table
          objectAlias: mpi-patient-table
          objectType: secret
        - |
          objectName: mpi-person-table
          objectAlias: mpi-person-table
          objectType: secret
    tenantId: <Tenant id, same as workspace id>              # The tenant ID of the key vault
