version: "3.9"
services:
  db:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=testdb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 5s
      retries: 20
  record-linkage:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MPI_DB_TYPE=postgres
      - MPI_DBNAME=DibbsMpiDB
      - MPI_HOST=phdidevmpi9d194c64.postgres.database.azure.com
      - MPI_PORT=5432
      - MPI_USER=postgres
      - MPI_PASSWORD=aFuydxPU2WZkHPbTmQL7sEkOD66Jp0Fm
      - MPI_PATIENT_TABLE=patient
      - MPI_PERSON_TABLE=person
    depends_on:
      db:
        condition: service_healthy
