version: "3.9"
services:
  db:
    image: "postgres:alpine"
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=testdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 20
  record-linkage:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      
  