name: Build Containers

on:
  pull_request:
    branches:
      - "**"
    paths:
      - "containers/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  list-containers:
    uses: ./.github/workflows/listContainers.yaml
  build:
    name: Build containers
    needs: list-containers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container-to-build: ${{fromJson(needs.list-containers.outputs.all-containers)}}
    steps:
      - name: Check Out Changes
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy shared-resources (if needed)
        if: ${{ matrix.container-to-build == 'ecr-viewer' }}
        working-directory: ./containers/${{matrix.container-to-build}}
        run: cp -r ../../shared-resources ./shared-resources

      - name: Target branch in requirements.txt
        working-directory: ./containers/${{matrix.container-to-build}}
        run: |
          if [ -f "requirements.txt" ]; then
            sed 's/phdi @ git+https:\/\/github.com\/CDCgov\/phdi.git@main/phdi @ git+https:\/\/github.com\/CDCgov\/phdi.git@${{ github.sha }}/g' requirements.txt > requirements_new.txt && mv requirements_new.txt requirements.txt
          fi

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./containers/${{matrix.container-to-build}}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            "INGESTION_URL=${{secrets.INGESTION_URL}}"
            "MESSAGE_PARSER_URL=${{secrets.MESSAGE_PARSER_URL}}"
            "SMARTY_AUTH_ID=${{secrets.SMARTY_AUTH_ID}}"
            "SMARTY_AUTH_TOKEN=${{secrets.SMARTY_AUTH_TOKEN}}"
