name: Test ecr-viewer Container

on:
  pull_request:
    branches:
      - "**"
    paths:
      - containers/ecr-viewer/**
  merge_group:
    types:
      - checks_requested
  push:
    branches:
      - main
    paths-ignore:
      - pyproject.toml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TEST_RUNNER_PYTHON_VERSION: 3.11
  CONTAINER: ecr-viewer
  NODE_VERSION: 18 # Adjust the Node.js version as needed

jobs:
  javascript-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint javascript for ${{env.CONTAINER}}
        working-directory: ./containers/${{env.CONTAINER}}
        run: |
          npm ci
          npm run lint
  test-node-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Install dependencies
        working-directory: ./containers/${{env.CONTAINER}} # Navigate to your Node.js app directory
        run: npm install
      - name: Run tests
        working-directory: ./containers/${{env.CONTAINER}} # Navigate to your Node.js app directory
        run: npm test
  cypress-e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Install dependencies
        working-directory: ./containers/${{env.CONTAINER}} # Navigate to your Node.js app directory
        run: npm install

      - name: Start ${{env.CONTAINER}}
        working-directory: ./containers/${{env.CONTAINER}}
        run: docker compose --env-file .env.test up -d

      - name: Wait for server to be ready
        run: |
          until $(curl --output /dev/null --silent --head --fail http://localhost:3000); do
            echo "Waiting for server to be ready..."
            sleep 5
          done

      - name: Run cypress tests
        working-directory: ./containers/${{env.CONTAINER}}
        run: npm run cypress:run
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check Out Changes
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build ${{ env.CONTAINER }} Container
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./containers/${{ env.CONTAINER }}/Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
