name: Debug Workflow

on:
  pull_request:
    branches:
      - "**"

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Is this working?
        id: is-this-working
        run: |
          echo "is this even working?"
