---
name: Generate Docs
run-name: Generate docs ${{ inputs.tag }} by @${{ github.actor }}
on:
  workflow_call:
    inputs:
      tag:
        description: Tag to deploy
        required: true
        type: string

concurrency:
  group: ${{ github.event.inputs.environment }}-generate-docs
  cancel-in-progress: false

jobs:
  list-containers:
    uses: ./.github/workflows/listContainers.yaml

  generate-and-update-container-docs:
    needs:
      - list-containers
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ${{ fromJson(needs.list-containers.outputs.python-containers) }}
    steps:
      - name: Check Out Changes
        uses: actions/checkout@v4

      - name: Update Container Documenation
        run: |
          npm i -g redoc-cli
          CONTAINER=${{ matrix.container }}
          cd $GITHUB_WORKSPACE/containers/$CONTAINER
          cp $GITHUB_WORKSPACE/utils/make_openapi_json.py .
          pip install -r requirements.txt
          python make_openapi_json.py
          redoc-cli build -o $GITHUB_WORKSPACE/docs/${{ inputs.tag }}/containers/$CONTAINER.html openapi.json

      - uses: actions/upload-artifact@v3
        with:
          name: container-docs
          path: ./docs/${{ inputs.tag }}/containers

  commit-docs:
    needs:
      - generate-and-update-container-docs
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: alis/tmp-docs

      - name: Download phdi docs from artifacts
        uses: actions/download-artifact@v2
        with:
          name: phdi-docs
          path: ./docs/${{ inputs.tag }}/sdk

      - name: Download container docs from artifacts
        uses: actions/download-artifact@v2
        with:
          name: container-docs
          path: ./docs/${{ inputs.tag }}/containers

      - name: Copy to latest folder
        run: |
          rm -rf ./docs/latest
          mkdir -p ./docs/latest/sdk
          mkdir -p ./docs/latest/containers
          cp -r ./docs/${{ inputs.tag }}/sdk/* ./docs/latest/sdk
          cp -r ./docs/${{ inputs.tag }}/containers/* ./docs/latest/containers

      - name: Commit New Documentation
        uses: EndBug/add-and-commit@v9
        with:
          add: docs
          message: Automated update of docs for ${{ inputs.tag }} release.