name: Lighthouse CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Change to the correct directory
        run: cd containers/ecr-viewer

      - name: Install dependencies
        run: npm install
        working-directory: ./containers/ecr-viewer

      - name: Build backend
        run: docker-compose up -d
        working-directory: ./containers/ecr-viewer/seed-scripts

      - name: Build frontend
        run: docker-compose up -d
        working-directory: ./containers/ecr-viewer

      - name: Wait for Application to be ready
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:3000; do
            printf '.'
            sleep 5
          done

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          # no urls needed, since it uses local folder to scan .html files
          configPath: "./lighthouserc.yaml"
