name: Lighthouse CI

on:
  push:
    branches:
      - main
    paths:
      - "containers/ecr-viewer/**"
  pull_request:
    branches:
      - main
    paths:
      - "containers/ecr-viewer/**"

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Remove symlinks
        working-directory: ./containers/ecr-viewer/src/app/shared
        run: rm -rf ./*

      - name: Copy shared-resources (if needed)
        working-directory: ./containers/ecr-viewer
        run: cp -r ../../shared-resources/src/ ./src/app/shared/src

      - name: Build app
        run: docker-compose up -d
        working-directory: ./containers/ecr-viewer

      - name: Wait for Application to be ready
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:3000; do
            printf '.'
            sleep 5
          done

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          configPath: "./lighthouserc.yaml"
          uploadArtifacts: true
