name: "List Containers"

on:
  workflow_call:
    outputs:
      containers: 
        value: ${{ jobs.list-containers.outputs.container-dirs }}
      integration-dirs:
        value: ${{ jobs.list-integration-test-directories.outputs.integration-dirs }}

jobs:
  list-containers:
    runs-on: ubuntu-latest
    outputs:
      container-dirs: ${{steps.generate-list.outputs.containers}}
    steps:
      - name: Check Out Changes
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get install jq
      - id: generate-list
        name: Generate list of directories within containers/
        working-directory: ./containers
        # use jq to produce json output and filter out the empty item caused by final newline
        run: |
          ls -d * | jq -R -s -c 'split("\n")[:-1]'
          containers_list=$(ls -d */ | cut -f1 -d'/' | jq -R -s -c 'split("\n")[:-1]')
          containers_list=$(echo "$containers_list" | jq 'map(select(. != "html-converter"))')
          echo "containers=$containers_list">> $GITHUB_OUTPUT
  list-integration-test-directories:
    runs-on: ubuntu-latest
    outputs:
      integration-dirs: ${{steps.generate-integration-list.outputs.containers_to_test}}
    steps:
      - name: Check Out Changes
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get install jq
      - id: generate-integration-list
        name: Generate list of integration test directories within containers/
        working-directory: ./containers
        run: |
          containers_to_test=$(find . -name "integration" -type d | cut -d "/" -f2 | jq -R -s -c 'split("\n")[:-1]' ) 
          containers_to_test=$(echo "$containers_to_test" | jq 'map(select(. != "html-converter"))')
          echo "containers_to_test=$containers_to_test">> $GITHUB_OUTPUT
