name: Publish to PyPI
if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

env:
  TEST_RUNNER_PYTHON_VERSION: 3.9

jobs:
  unit-test-phdi-building-blocks-lib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python ${{env.TEST_RUNNER_PYTHON_VERSION}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.TEST_RUNNER_PYTHON_VERSION}}
          cache: pip
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: poetry install
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Build source and wheels archives & dry run of publication
        run: |
          poetry publish --username [username to access the repository] --password [pw for repo] --build --dry-run
      - name: Publish package to PyPI
        run: |
          poetry publish --username [username to access the repository] --password [pw for repo]


