name: Pull Request CI

on:
  pull_request:
    branches:
      - "**"

jobs:
  determine-changes:
    uses: ./.github/workflows/determineChanges.yaml
    outputs:
      changed-files-data: ${{ steps.determine-changes.outputs.changed-files-data }}

  lint-changed-files:
    needs: determine-changes
    runs-on: ubuntu-latest
    steps:
      - name: Call Lint Workflow
        uses: ./.github/workflows/lint.yaml
        with:
          changed-files-data: ${{ needs.determine-changes.outputs.changed-files-data }}
