name: Pull Request CI

on:
  pull_request:
    branches:
      - "**"

jobs:
  determine-changes:
    uses: ./.github/workflows/determineChanges.yaml

  lint-changed-files:
    needs: determine-changes
    uses: ./.github/workflows/lintChangedFiles.yaml
    with:
      changed-files-data: ${{ needs.determine-changes.outputs.changed-files-data }}

  test-changed-files:
    needs: determine-changes
    uses: ./.github/workflows/testChangedFiles.yaml
    with:
      changed-files-data: ${{ needs.determine-changes.outputs.changed-files-data }}
