name: "Run Container Workflow"
description: "Runs a specified container workflow"

inputs:
  workflow:
    description: "The workflow file to run"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run specified workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh workflow run .github/workflows/container-${{ inputs.workflow }}.yaml
