name: Test and Tag Release
on:
  workflow_dispatch:
    inputs:
      custom_tag:
        description: "Enter version number for release tag below. Don't forget the v! Example: v2.23.9"
        type: string
        required: true
  push:
    branches: gordon/automated-release-workflow

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  create-tagged-release:
    needs: test
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Update version and push tag
        uses: anothrNick/github-tag-action@1.55.0 # Don't use @master unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ github.event.inputs.custom_tag }}