name: Test DIBBs Container
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"
    paths:
      - containers/dibbs/**
  merge_group:
    types:
      - checks_requested
  push:
    branches:
      - main
    paths-ignore:
      - pyproject.toml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TEST_RUNNER_PYTHON_VERSION: 3.10.12
  CONTAINER: dibbs

jobs:
  python-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python ${{env.TEST_RUNNER_PYTHON_VERSION}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.TEST_RUNNER_PYTHON_VERSION}}
          cache: pip
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install ruff==0.4.3
      - name: Run linter (ruff)
        run: |
          ruff check --output-format=github .
      - name: Run formatter (ruff)
        run: |
          ruff format --check
  unit-test-python-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python ${{env.TEST_RUNNER_PYTHON_VERSION}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.TEST_RUNNER_PYTHON_VERSION}}
          cache: pip
      - name: Install pytest
        run: pip install pytest
      - name: Install dependencies
        working-directory: ./containers/${{env.CONTAINER}}
        run: |
          pip install .
          pip install -r requirements.txt
          if [ -f dev-requirements.txt ]; then
            pip install -r dev-requirements.txt
          fi
      - name: Run unit tests for container
        working-directory: ./containers/${{env.CONTAINER}}
        run: |
          python -m pytest -m "not integration"
