name: Test Changed Files

on:
  workflow_call:
    inputs:
      changed-files-data:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TEST_RUNNER_PYTHON_VERSION: 3.10.12

jobs:
  filter-test-files:
    runs-on: ubuntu-latest
    outputs:
      sdk-changed: ${{ steps.filter-test-files.outputs.sdk-changed }}
      container-changes: ${{ steps.filter-test-files.outputs.container-changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Determine changes
        id: filter-test-files
        run: |
          CHANGED_FILES_JSON='${{ inputs.changed-files-data }}'
          # determine if code or tests for the sdk have changed
          echo "sdk-changed=$(echo $CHANGED_FILES_JSON | \
            jq -r '[.[] | select(.tag == "sdk")] | length > 0')" >> $GITHUB_OUTPUT
          # get changed container apps with their metadata
          echo "container-changes=$(echo $CHANGED_FILES_JSON | \
            jq -c '[.[] | select(.tag == "container") | \
            {name: .container_name, requirements_txt: .requirements_txt, \
            package_json: .package_json, needs_postgres: .needs_postgres}]')" >> $GITHUB_OUTPUT

  run-tests:
    needs: filter-test-files
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.filter-test-files.outputs.container-changes)}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # setup python if any container requires it
      - name: Setup Python
        if: contains(matrix.requirements_txt, 'true')
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.TEST_RUNNER_PYTHON_VERSION }}

      # setup node.js if any container requires it
      - name: Setup Node.js
        if: contains(matrix.package_json, 'true')
        uses: actions/setup-node@v2
        with:
          node-version: 18

      # add steps for running tests in the specific container
      - name: Run Python container tests
        if: contains(matrix.requirements_txt, 'true')
        run: |
          echo "Running Python tests for container ${matrix.name}"

      - name: Run JavaScript container tests
        if: contains(matrix.package_json, 'true')
        run: |
          echo "Running JavaScript tests for container ${matrix.name}"
