name: Update Conainter Documentation
on:
  workflow_dispatch:
  push:
    paths:
      - "containers/**"
      - ".github/workflows/updateContainerDocumentation.yml"
      - ".github/workflows/listContainers.yml"

jobs:
  list-all-containers:
    uses: ./.github/workflows/listContainers.yml
  test-job:
    name: Test Job
    needs: list-all-containers
    runs-on: ubuntu-latest
    steps:
      - name: Log containers var
        run: |
          echo ${{ needs.list-all-containers.outputs.containers }}
  update-docs:
    name: Update Docs
    needs: list-all-containers
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Changes
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Generate Documenation
        working-directory: ./containers/${{matrix.container}}
        run: |
          npm i -g redoc-cli
          container_list=$(echo "$containers" | sed 's/[][]//g' | sed 's/,/ /g')
          for CONTAINER in "${container_list[@]}"
          do
            cd phdi/containers/$CONTAINER
            cp ../make_openapi_json.py .
            pip install -r requirements.txt
            python make_openapi_json.py
            redoc-cli build -o documentation.html openapi.json
          done
      - name: Commit New Documentation
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.html'
          message: Update container documentation.
          committer_name: GitHub Actions
          committer_email: actions@github.com
